PREQUEL=${prequel_bin}
ARGS=--top 25 --commits ${COMMIT}..v4.6 --git /run/shm/linux \
--u0mindex ${indices_dir}/linux_idutils_minus_word_U0.index \
--u0pindex ${indices_dir}/linux_idutils_plus_word_U0.index \
--ref /run/shm/linux-4.6 --cores ${nb_cores} -o $@.porg --tmp /run/shm/${NAME}_$@ \
--all-lines --ignore ${FILE}
RARGS=--commits ${COMMIT}..v4.6 --git /run/shm/linux \
--word-filter \
--ref /run/shm/linux --cores ${nb_cores} -o $@.porg --tmp /run/shm/${NAME}_$@ --all-lines \
--ignore ${FILE}

