PREQUEL=/home/julia/prequel/src/prequel.opt
ARGS=--top 25 --commits COMMIT..v4.6 --git /run/shm/linux \
--u0mindex /home/julia/prequel/indices/linux_idutils_minus_word_U0.index \
--u0pindex /home/julia/prequel/indices/linux_idutils_plus_word_U0.index \
--ref /run/shm/linux-4.6 --cores 48 -o $@.porg --tmp /run/shm/NAME_$@ \
--all-lines --ignore FILE
RARGS=--commits COMMIT..v4.6 --git /run/shm/linux \
--word-filter \
--ref /run/shm/linux --cores 48 -o $@.porg --tmp /run/shm/NAME_$@ --all-lines \
--ignore FILE

